version: "3"
services:
  db:
    image: aact
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aact_db
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_USER=aact
      - POSTGRES_PASSWORD=postgres
